version: '3.8'

volumes:
    postgres_data:
    static:
    media:
    nginx_conf:

services:

  db:
    image: postgres:12.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  django:
    image: azeron/foodgram:latest
    depends_on:
      - db
    restart: always
    env_file:
      - ./.env
    volumes:
        - static:/code/static
        - media:/code/media
        - nginx_conf:/code/conf/
    entrypoint: /code/entrypoint.sh

  nginx:
    image: nginx:latest
    ports:
      - "127.0.0.1:8888:80"
    volumes:
      - static:/code/static
      - media:/code/media
      - nginx_conf:/etc/nginx/conf.d/
    depends_on:
      - django
    restart: always