# Generated by Django 3.1.7 on 2021-05-02 14:37

from django.db import migrations
import csv


def put_ingredients(apps, schema_editor):
    Ingredient = apps.get_model('dishes', 'Ingredient')

    with open('ingredients.csv', 'r', newline='', encoding='utf-8') as csvfile:
        csvreader = csv.reader(csvfile)
        for row in csvreader:
            Ingredient.objects.get_or_create(
                name=row[0],
                measure=row[-1],
            )


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(put_ingredients),
    ]
