# Generated by Django 3.1.7 on 2021-05-02 14:37

import csv

from django.db import migrations


def put_data(apps, schema_editor):

    Ingredient = apps.get_model('dishes', 'Ingredient')
    Tag = apps.get_model('dishes', 'Tag')

    tags = [
        {
            'name': 'breakfast',
            'visual_name': 'завтрак',
            'color': 'green',
        },
        {
            'name': 'lunch',
            'visual_name': 'обед',
            'color': 'orange',
        },
        {
            'name': 'dinner',
            'visual_name': 'ужин',
            'color': 'purple',
        }
    ]
    for tag in tags:
        Tag.objects.get_or_create(
            name=tag['name'],
            visual_name=tag['visual_name'],
            color=tag['color'],
        )

    with open('ingredients.csv', 'r', newline='', encoding='utf-8') as csvfile:
        csvreader = csv.reader(csvfile)
        for row in csvreader:
            Ingredient.objects.get_or_create(
                name=row[0],
                measure=row[-1],
            )


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(put_data),
    ]
