# Generated by Django 3.1.7 on 2021-04-29 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='basket',
            new_name='purchases',
        ),
    ]
