# Generated by Django 3.1.7 on 2021-04-10 14:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dishes', '0002_auto_20210410_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='is_favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite', to=settings.AUTH_USER_MODEL, verbose_name='Избранное'),
        ),
    ]
