# Generated by Django 3.1.7 on 2021-03-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_auto_20210317_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True, verbose_name='Ссылка'),
        ),
    ]
