# Generated by Django 3.1.7 on 2021-04-12 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dishes', '0003_auto_20210410_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='shoplist',
        ),
        migrations.AddField(
            model_name='recipe',
            name='basket',
            field=models.ManyToManyField(blank=True, related_name='basket', to=settings.AUTH_USER_MODEL, verbose_name='Корзина'),
        ),
    ]
