# Generated by Django 3.1.7 on 2021-03-18 09:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dishes', '0003_auto_20210317_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='basket',
            field=models.ManyToManyField(blank=True, related_name='basket', to=settings.AUTH_USER_MODEL, verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='is_favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite', to=settings.AUTH_USER_MODEL, verbose_name='Избранное'),
        ),
    ]
