# Generated by Django 3.1.7 on 2021-04-27 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_auto_20210418_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ингердиент', 'verbose_name_plural': 'Ингердиенты'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AlterModelOptions(
            name='volume',
            options={'verbose_name': 'Ингредиенты рецептов', 'verbose_name_plural': 'Ингредиенты рецептов'},
        ),
    ]
