# Generated by Django 3.1.7 on 2021-03-20 13:19

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0005_auto_20210320_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, editable=True, populate_from='name', unique=True, verbose_name='ссылка'),
        ),
    ]
