# Generated by Django 3.1.7 on 2021-03-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0007_auto_20210320_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True, verbose_name='Ссылка'),
        ),
    ]
