# Generated by Django 3.1.7 on 2021-04-27 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0009_auto_20210427_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Все ингредиенты'},
        ),
    ]
