# Generated by Django 3.1.7 on 2021-03-10 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_01_dishes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='basket',
            field=models.ManyToManyField(related_name='recipe_basket', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_favorite',
            field=models.ManyToManyField(related_name='recipe_favorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(db_index=True, related_name='recipe', through='app_01_dishes.Volume', to='app_01_dishes.Ingredient', verbose_name='Ингридиенты'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(db_index=True, related_name='recipe', to='app_01_dishes.Tag', verbose_name='Тэг'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='id_ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume', to='app_01_dishes.ingredient'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='id_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume', to='app_01_dishes.recipe'),
        ),
    ]
